#!/usr/bin/env python3
"""
生成 Cephes 精度验证 C++ 头文件。
用 scipy 计算参考值，导出为 C++ 数组 + 比较函数到 cephes_ref.inc。

用法:
  python check_cephes.py          # 生成 cephes_ref.inc
  python check_cephes.py --check  # 生成后编译并运行 C++ 测试
"""

import sys
import subprocess
import numpy as np
from scipy import special as sp

kNum = 1024


def _format_float(val: float, dtype: str) -> str:
    if np.isinf(val) or np.isnan(val):
        # 用极大有限值代替 inf/nan，保持 C++ 数组可编译
        if dtype == "float":
            return "3.4028234663852886e+38f"  # FLT_MAX
        else:
            return "1.7976931348623157e+308"  # DBL_MAX / MAXNUM
    if dtype == "float":
        return f"{val:.10e}f"
    else:
        return f"{val:.16e}"


def _format_array(arr: np.ndarray, name: str) -> str:
    """生成 C++ constexpr 数组定义"""
    dtype_cpp = "float" if arr.dtype == np.float32 else "double"
    lines = [f"static constexpr {dtype_cpp} kRef_{name}[kRefNum] = {{"]
    vals_per_line = 6 if dtype_cpp == "double" else 8
    vals = []
    for v in arr:
        vals.append(_format_float(float(v), dtype_cpp))
    for i in range(0, len(vals), vals_per_line):
        chunk = vals[i : i + vals_per_line]
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def gen_cpp_header(ref: dict) -> str:
    """生成 C++ 头文件内容"""
    lines = []
    lines.append("// Auto-generated by check_cephes.py -- do not edit manually")
    lines.append(f"// Generated with scipy {sp.__version__ if hasattr(sp, '__version__') else '?'}")
    lines.append("#pragma once")
    lines.append("#include <cstdio>")
    lines.append("#include <cmath>")
    lines.append("#include <algorithm>")
    lines.append("")
    lines.append(f"static constexpr int kRefNum = {kNum};")
    lines.append("")

    # 排序 key，先 float 后 double
    float_keys = sorted(k for k in ref if ref[k].dtype == np.float32)
    double_keys = sorted(k for k in ref if ref[k].dtype == np.float64)

    lines.append("// ── float 参考 ──")
    lines.append("")
    for name in float_keys:
        lines.append(_format_array(ref[name], name))
        lines.append("")

    lines.append("// ── double 参考 ──")
    lines.append("")
    for name in double_keys:
        lines.append(_format_array(ref[name], name))
        lines.append("")

    # 生成比较函数
    lines.append("// ── 比较函数 ──")
    lines.append("")
    lines.append("template<class T>")
    lines.append("static int CheckRef(const char* name, const T* computed, const T* ref, int n,")
    lines.append("                      T abs_tol, T rel_tol) noexcept {")
    lines.append("    int errs = 0;")
    lines.append("    T max_abs_err = 0, max_rel_err = 0;")
    lines.append("    for (int i = 0; i < n; ++i) {")
    lines.append("        T abs_err = std::abs(computed[i] - ref[i]);")
    lines.append("        T rel_err = abs_err / (std::abs(ref[i]) + T(1e-30));")
    lines.append("        max_abs_err = std::max(max_abs_err, abs_err);")
    lines.append("        max_rel_err = std::max(max_rel_err, rel_err);")
    lines.append("        if (abs_err > abs_tol && rel_err > rel_tol)")
    lines.append("            ++errs;")
    lines.append("    }")
    lines.append("    std::printf(\"  %-14s  n=%4d  max_abs_err=%8.2e  max_rel_err=%8.2e  errs=%d\\n\",")
    lines.append("               name, n, double(max_abs_err), double(max_rel_err), errs);")
    lines.append("    return errs;")
    lines.append("}")
    lines.append("")

    # 生成批量验证函数
    lines.append("// ── 批量验证 ──")
    lines.append("")
    lines.append("template<int N, class T, class Fn>")
    lines.append("static int CheckAll(Fn fn, T* buf) noexcept {")
    lines.append("    int total_errs = 0;")
    lines.append("    for (int i = 0; i < N; ++i)")
    lines.append("        buf[i] = fn(T(i) / T(N));")
    lines.append("    return total_errs;")
    lines.append("}")

    return "\n".join(lines)


def gen_ref():
    """生成 scipy 参考数组"""
    ref = {}
    t = np.arange(kNum) / kNum

    # Besself (float)
    ref["bf_i0"] = sp.i0(10.0 * t).astype(np.float32)
    ref["bf_i1"] = sp.i1(10.0 * t).astype(np.float32)

    # Ellipticf (float)
    m1_pk = (np.arange(kNum, dtype=float) + 1.0) / kNum
    ref["ef_ellpk"] = sp.ellipk(1.0 - m1_pk).astype(np.float32)
    ref["ef_ellpe"] = sp.ellipe(1.0 - t).astype(np.float32)

    phi = 2.0 * t
    ref["ef_ellik"] = sp.ellipkinc(phi, 0.5).astype(np.float32)
    ref["ef_ellie"] = sp.ellipeinc(phi, 0.5).astype(np.float32)

    u = 10.0 * t
    sn, cn, dn, ph = sp.ellipj(u, 0.5)
    ref["ef_sn"] = sn.astype(np.float32)
    ref["ef_cn"] = cn.astype(np.float32)
    ref["ef_dn"] = dn.astype(np.float32)
    ref["ef_ph"] = ph.astype(np.float32)

    # Bessel (double)
    ref["b_i0"] = sp.i0(30.0 * t)
    ref["b_i1"] = sp.i1(30.0 * t)

    # Elliptic (double)
    ref["e_ellpk"] = sp.ellipk(1.0 - t)
    ref["e_ellpe"] = sp.ellipe(1.0 - t)
    ref["e_ellik"] = sp.ellipkinc(phi, 0.5)
    ref["e_ellie"] = sp.ellipeinc(phi, 0.5)
    e_sn, e_cn, e_dn, e_ph = sp.ellipj(u, 0.5)
    ref["e_sn"] = e_sn
    ref["e_cn"] = e_cn
    ref["e_dn"] = e_dn
    ref["e_ph"] = e_ph

    return ref


def main():
    ref = gen_ref()
    header = gen_cpp_header(ref)

    out_path = "cephes_ref.inc"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"已生成 {out_path}")
    print(f"  float 数组: {sum(1 for a in ref if ref[a].dtype == np.float32)} 个")
    print(f"  double 数组: {sum(1 for a in ref if ref[a].dtype == np.float64)} 个")

    if "--check" in sys.argv:
        print("\n运行 cmake build 验证...")
        result = subprocess.run(
            ["cmake", "--build", ".", "--target", "qwqdsp-cephes"],
            cwd=r"C:\Users\Kawai\Desktop\a5632645\qwqdsp\build",
            capture_output=True, text=True
        )
        if result.returncode != 0:
            print("编译失败:")
            print(result.stderr[-500:])
        else:
            result2 = subprocess.run(
                [r".\qwqdsp\tests\Debug\qwqdsp-cephes.exe"],
                cwd=r"C:\Users\Kawai\Desktop\a5632645\qwqdsp\build",
                capture_output=True, text=True
            )
            print(result2.stdout)
            if result2.stderr:
                print(result2.stderr[-500:])


if __name__ == "__main__":
    main()
