# ------------------------------------------------------------
# DSP 测试（无 GUI）分发
# ------------------------------------------------------------
add_subdirectory(cephes)
add_subdirectory(filter)
add_subdirectory(audiofx)
add_subdirectory(spectral)
add_subdirectory(pitch)
add_subdirectory(synth)
add_subdirectory(oneset)
